extend-exclude = [
    "*.md",
    ".git",
    ".pyenv",
    ".ruff_cache",
    "config",
    "database",
    "node_module",
    "public",
    "resources",
    "routes",
    "site_packages",
    "storage",
    "vendor",
    "venv",
]

line-length = 88
indent-width = 4

[lint]
# See ruff lint rule abbreviations at https://docs.astral.sh/ruff/rules/
select = ["E", "F", "B", "S", "A", "COM", "C4", "T10", "EM", "ISC", "ICN", "LOG", "INP", "PIE", "T20", "PLE", "RUF"]
ignore = ["COM812"]
fixable = ["ALL"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "single"
line-ending = "auto"
indent-style = "space"
skip-magic-trailing-comma = false
