<?php

/*
    Format:

    'language' => [
        'linguacafe_support' => bool, // can this language be learned in linguacafe 
        'tokenizer' => null|string, // name of the tokenizer if linguacafe_supported, otherwise null
        'install_required' => bool,
        'words_separated_by_spaces' => bool,
        'deepl_code' => null|string, // deepl code if supported, otherwise null
        'libre_translate_code' => null|string, // libre translate code if supported, otherwise null
        'my_memory_code' => null|string, // mymemory code if supported, otherwise null
        'website_import_support' => bool,
        'jellyfin_code' => null|string, // jellyfin code if supported, otherwise null
        'database_dictionary_table_name' => null|string,
    ];


    jellyfin_code note:
    These are language codes that Jellyfin uses for subtitles. You can find out what
    a Jellyfin language code is by going to the Jellyfin subtitle import, and starting a video
    with a new language subtitle. If that new language is not added here, you will see
    a javascript log about unsupported languages code.

    missing information note:
    Some languages have partial information, so I just added them commented out to be used later.

*/


return [
    'albanian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => 'sq',
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'sq',
    ],
    'arabic' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'AR',
        'libre_translate_code' => 'ar',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => null,
    ],
    // 'belarusian' => [
    //     'website_import_support' => true,
    // ],
    'bosnian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'bs',
    ],
    'brazilian portuguese' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'PT-BR',
        'libre_translate_code' => null,
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => null,
    ],
    'bulgarian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'stanza',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'BG',
        'libre_translate_code' => 'bg',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'bg',
    ],
    'catalan' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => 'ca',
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'ca',
    ],
    'chinese' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => false,
        'deepl_code' => 'ZH',
        'libre_translate_code' => 'zh',
        'my_memory_code' => 'zh-CN',
        'website_import_support' => true,
        'jellyfin_code' => 'chi',
        'database_dictionary_table_name' => 'zh',
    ],
    'croatian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'hr-HR',
        'website_import_support' => true,
        'jellyfin_code' => 'hrv',
        'database_dictionary_table_name' => 'hr',
    ],
    'czech' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'CZ',
        'libre_translate_code' => 'cs',
        'my_memory_code' => 'cs',
        'website_import_support' => false,
        'jellyfin_code' => 'cze',
        'database_dictionary_table_name' => 'cs',
    ],
    'danish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'DA',
        'libre_translate_code' => 'da',
        'my_memory_code' => 'da-DE',
        'website_import_support' => true,
        'jellyfin_code' => 'dan',
        'database_dictionary_table_name' => 'da',
    ],
    'dutch' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'NL',
        'libre_translate_code' => 'nl',
        'my_memory_code' => 'nl-NL',
        'website_import_support' => true,
        'jellyfin_code' => 'dut',
        'database_dictionary_table_name' => 'nl',
    ],
    'english' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'EN-US',
        'libre_translate_code' => 'en',
        'my_memory_code' => 'en-GB',
        'website_import_support' => true,
        'jellyfin_code' => 'eng',
        'database_dictionary_table_name' => 'en',
    ],
    'esperanto' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => 'eo',
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'eo',
    ],
    'estonian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'ET',
        'libre_translate_code' => 'et',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => null,
    ],
    'finnish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'FI',
        'libre_translate_code' => 'fi',
        'my_memory_code' => 'fi-FI',
        'website_import_support' => true,
        'jellyfin_code' => 'fin',
        'database_dictionary_table_name' => 'fi',
    ],
    'french' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'FR',
        'libre_translate_code' => 'fr',
        'my_memory_code' => 'fr-FR',
        'website_import_support' => true,
        'jellyfin_code' => 'fre',
        'database_dictionary_table_name' => 'fr',
    ],
    'german' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'DE',
        'libre_translate_code' => 'de',
        'my_memory_code' => 'de-DE',
        'website_import_support' => true,
        'jellyfin_code' => 'ger',
        'database_dictionary_table_name' => 'de',
    ],
    'greek' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'EL',
        'libre_translate_code' => 'el',
        'my_memory_code' => 'el-GR',
        'website_import_support' => true,
        'jellyfin_code' => 'gre',
        'database_dictionary_table_name' => 'el',
    ],
    // 'hebrew' => [
    //     'website_import_support' => true,
    // ],
    // 'hindi' => [
    //     'website_import_support' => true,
    // ],
    'hungarian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'HU',
        'libre_translate_code' => 'hu',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'hu',
    ],
    'icelandic' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'is',
    ],
    'indonesian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'ID',
        'libre_translate_code' => 'id',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => null,
    ],
    'italian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'IT',
        'libre_translate_code' => 'it',
        'my_memory_code' => 'it-IT',
        'website_import_support' => true,
        'jellyfin_code' => 'ita',
        'database_dictionary_table_name' => 'it',
    ],
    'japanese' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => false,
        'deepl_code' => 'JA',
        'libre_translate_code' => 'ja',
        'my_memory_code' => 'ja',
        'website_import_support' => true,
        'jellyfin_code' => 'jpn',
        'database_dictionary_table_name' => 'jp',
    ],
    'korean' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'KO',
        'libre_translate_code' => 'ko',
        'my_memory_code' => 'ko-KR',
        'website_import_support' => true,
        'jellyfin_code' => 'kor',
        'database_dictionary_table_name' => 'ko',
    ],
    'latin' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'la',
        'website_import_support' => false,
        'jellyfin_code' => 'lat',
        'database_dictionary_table_name' => 'la',
    ],
    'latvian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'LV',
        'libre_translate_code' => 'lv',
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => null,
    ],
    'lithuanian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'LT',
        'libre_translate_code' => 'lt',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => 'lit',
        'database_dictionary_table_name' => 'lt',
    ],
    'macedonian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'mk',
        'website_import_support' => true,
        'jellyfin_code' => 'mac',
        'database_dictionary_table_name' => 'mk',
    ],
    'norwegian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'NB',
        'libre_translate_code' => 'nb',
        'my_memory_code' => 'no',
        'website_import_support' => true,
        'jellyfin_code' => 'nor',
        'database_dictionary_table_name' => 'no',
    ],
    // 'persian' => [
    //     'website_import_support' => true,
    // ],
    'polish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'PL',
        'libre_translate_code' => 'pl',
        'my_memory_code' => 'pl',
        'website_import_support' => true,
        'jellyfin_code' => 'pol',
        'database_dictionary_table_name' => 'pl',
    ],
    'portuguese' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'PT-PT',
        'libre_translate_code' => 'pt',
        'my_memory_code' => 'pt-PT',
        'website_import_support' => true,
        'jellyfin_code' => 'por',
        'database_dictionary_table_name' => 'pt',
    ],
    'romanian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'RO',
        'libre_translate_code' => 'ro',
        'my_memory_code' => 'ro',
        'website_import_support' => true,
        'jellyfin_code' => 'rum', // rum is not a misspell
        'database_dictionary_table_name' => 'ro',
    ],
    'russian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'RU',
        'libre_translate_code' => 'ru',
        'my_memory_code' => 'ru-RU',
        'website_import_support' => true,
        'jellyfin_code' => 'rus',
        'database_dictionary_table_name' => 'ru',
    ],
    'serbian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => 'sr',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'sr',
    ],
    'slovak' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'SK',
        'libre_translate_code' => 'sk',
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'sk',
    ],
    'slovenian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'SL',
        'libre_translate_code' => 'sl',
        'my_memory_code' => 'sl',
        'website_import_support' => true,
        'jellyfin_code' => 'slv',
        'database_dictionary_table_name' => 'sl',
    ],
    'spanish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'ES',
        'libre_translate_code' => 'es',
        'my_memory_code' => 'es-ES',
        'website_import_support' => true,
        'jellyfin_code' => 'spa',
        'database_dictionary_table_name' => 'es',
    ],
    // 'swahili' => [
    //     'website_import_support' => true,
    // ],
    'swedish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'SV',
        'libre_translate_code' => 'sv',
        'my_memory_code' => 'sv-SE',
        'website_import_support' => true,
        'jellyfin_code' => 'swe',
        'database_dictionary_table_name' => 'sv',
    ],
    'thai' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => false,
        'deepl_code' => null,
        'libre_translate_code' => 'th',
        'my_memory_code' => 'th',
        'website_import_support' => false,
        'jellyfin_code' => 'tha',
        'database_dictionary_table_name' => 'th',
    ],
    'turkish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'TR',
        'libre_translate_code' => 'tr',
        'my_memory_code' => 'tr-TR',
        'website_import_support' => true,
        'jellyfin_code' => 'tur',
        'database_dictionary_table_name' => 'tr',
    ],
    'ukrainian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'UK',
        'libre_translate_code' => 'uk',
        'my_memory_code' => 'uk',
        'website_import_support' => true,
        'jellyfin_code' => 'ukr',
        'database_dictionary_table_name' => 'ua',
    ],
    // 'vietnamese' => [
    //     'website_import_support' => true,
    // ],
    'welsh' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'cy-GB',
        'website_import_support' => false,
        'jellyfin_code' => 'wel',
        'database_dictionary_table_name' => 'cy',
    ],
];