<?php

/*
    Format:

    'language' => [
        'linguacafe_support' => bool, // can this language be learned in linguacafe 
        'tokenizer' => null|string, // name of the tokenizer if linguacafe_supported, otherwise null
        'install_required' => bool,
        'words_separated_by_spaces' => bool,
        'deepl_code' => null|string, // deepl code if supported, otherwise null
        'libre_translate_code' => null|string, // libre translate code if supported, otherwise null
        'my_memory_code' => null|string, // mymemory code if supported, otherwise null
        'website_import_support' => bool,
        'jellyfin_code' => null|string, // jellyfin code if linguacafe_support is true, otherwise null. should be added if missing
        'database_dictionary_table_name' => null|string, // database table slug if linguacafe_support is true, otherwise null. must be added if missing
        'dict_cc_code' => null|string, // dict cc code if supported, otherwise null
        'unicode_emoji' => string, // unicode emoji flag of the language. sometimes this does not match with the flag image in LC. '-' if there's no emoji
    ];


    jellyfin_code note:
    These are language codes that Jellyfin uses for subtitles. You can find out what
    a Jellyfin language code is by going to the Jellyfin subtitle import, and starting a video
    with a new language subtitle. If that new language is not added here, you will see
    a javascript log about unsupported languages code.

    missing information note:
    Some languages have partial information, so I just added them commented out to be used later.

*/


return [
    'afrikaans' => [
        'linguacafe_support' => true,
        'tokenizer' => 'stanza',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'af',
        'website_import_support' => false,
        'jellyfin_code' => 'afr',
        'database_dictionary_table_name' => 'af',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇿🇦',
    ],
    'albanian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => 'sq',
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'sq',
        'dict_cc_code' => 'SQ',
        'unicode_emoji' => '🇦🇱',
    ],
    'arabic' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'AR',
        'libre_translate_code' => 'ar',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => null,
        'dict_cc_code' => null,
        'unicode_emoji' => '🇸🇦',
    ],
    'armenian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'stanza',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'hy',
        'website_import_support' => false,
        'jellyfin_code' => 'hye',
        'database_dictionary_table_name' => 'hye',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇦🇲',
    ],
    'basque' => [
        'linguacafe_support' => true,
        'tokenizer' => 'stanza',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => 'eu',
        'my_memory_code' => 'eu',
        'website_import_support' => false,
        'jellyfin_code' => 'eus',
        'database_dictionary_table_name' => 'eus',
        'dict_cc_code' => null,
        'unicode_emoji' => '-',
    ],
    'belarusian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'stanza',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'be',
        'website_import_support' => true,
        'jellyfin_code' => 'bel',
        'database_dictionary_table_name' => 'bel',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇧🇾',
    ],
    'bosnian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'bs',
        'dict_cc_code' => 'BS',
        'unicode_emoji' => '🇧🇦',
    ],
    'brazilian portuguese' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'PT-BR',
        'libre_translate_code' => null,
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => null,
        'dict_cc_code' => null,
        'unicode_emoji' => '🇧🇷',
    ],
    'bulgarian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'stanza',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'BG',
        'libre_translate_code' => 'bg',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'bg',
        'dict_cc_code' => 'BG',
        'unicode_emoji' => '🇧🇬',
    ],
    'catalan' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => 'ca',
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'ca',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇦🇩',
    ],
    'chinese' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => false,
        'deepl_code' => 'ZH',
        'libre_translate_code' => 'zh',
        'my_memory_code' => 'zh-CN',
        'website_import_support' => true,
        'jellyfin_code' => 'chi',
        'database_dictionary_table_name' => 'zh',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇨🇳',
    ],
    'croatian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'hr-HR',
        'website_import_support' => true,
        'jellyfin_code' => 'hrv',
        'database_dictionary_table_name' => 'hr',
        'dict_cc_code' => 'HR',
        'unicode_emoji' => '🇭🇷',
    ],
    'czech' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'CZ',
        'libre_translate_code' => 'cs',
        'my_memory_code' => 'cs',
        'website_import_support' => false,
        'jellyfin_code' => 'cze',
        'database_dictionary_table_name' => 'cs',
        'dict_cc_code' => 'CS',
        'unicode_emoji' => '🇨🇿',
    ],
    'danish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'DA',
        'libre_translate_code' => 'da',
        'my_memory_code' => 'da-DE',
        'website_import_support' => true,
        'jellyfin_code' => 'dan',
        'database_dictionary_table_name' => 'da',
        'dict_cc_code' => 'DA',
        'unicode_emoji' => '🇩🇰',
    ],
    'dutch' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'NL',
        'libre_translate_code' => 'nl',
        'my_memory_code' => 'nl-NL',
        'website_import_support' => true,
        'jellyfin_code' => 'dut',
        'database_dictionary_table_name' => 'nl',
        'dict_cc_code' => 'NL',
        'unicode_emoji' => '🇳🇱',
    ],
    'english' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'EN-US',
        'libre_translate_code' => 'en',
        'my_memory_code' => 'en-GB',
        'website_import_support' => true,
        'jellyfin_code' => 'eng',
        'database_dictionary_table_name' => 'en',
        'dict_cc_code' => 'EN',
        'unicode_emoji' => '🇬🇧',
    ],
    'esperanto' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => 'eo',
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'eo',
        'dict_cc_code' => 'EO',
        'unicode_emoji' => '-',
    ],
    'estonian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'ET',
        'libre_translate_code' => 'et',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => null,
        'dict_cc_code' => null,
        'unicode_emoji' => '🇪🇪',
    ],
    'finnish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'FI',
        'libre_translate_code' => 'fi',
        'my_memory_code' => 'fi-FI',
        'website_import_support' => true,
        'jellyfin_code' => 'fin',
        'database_dictionary_table_name' => 'fi',
        'dict_cc_code' => 'FI',
        'unicode_emoji' => '🇫🇮',
    ],
    'french' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'FR',
        'libre_translate_code' => 'fr',
        'my_memory_code' => 'fr-FR',
        'website_import_support' => true,
        'jellyfin_code' => 'fre',
        'database_dictionary_table_name' => 'fr',
        'dict_cc_code' => 'FR',
        'unicode_emoji' => '🇫🇷',
    ],
    'german' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'DE',
        'libre_translate_code' => 'de',
        'my_memory_code' => 'de-DE',
        'website_import_support' => true,
        'jellyfin_code' => 'ger',
        'database_dictionary_table_name' => 'de',
        'dict_cc_code' => 'DE',
        'unicode_emoji' => '🇩🇪',
    ],
    'greek' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'EL',
        'libre_translate_code' => 'el',
        'my_memory_code' => 'el-GR',
        'website_import_support' => true,
        'jellyfin_code' => 'gre',
        'database_dictionary_table_name' => 'el',
        'dict_cc_code' => 'EL',
        'unicode_emoji' => '🇬🇷',
    ],
    // 'hebrew' => [
    //     'website_import_support' => true,
    // ],
    // 'hindi' => [
    //     'website_import_support' => true,
    // ],
    'hungarian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'HU',
        'libre_translate_code' => 'hu',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'hu',
        'dict_cc_code' => 'HU',
        'unicode_emoji' => '🇭🇺',
    ],
    'icelandic' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'is',
        'dict_cc_code' => 'IS',
        'unicode_emoji' => '🇮🇸',
    ],
    'indonesian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'ID',
        'libre_translate_code' => 'id',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => null,
        'dict_cc_code' => null,
        'unicode_emoji' => '🇮🇩',
    ],
    'italian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'IT',
        'libre_translate_code' => 'it',
        'my_memory_code' => 'it-IT',
        'website_import_support' => true,
        'jellyfin_code' => 'ita',
        'database_dictionary_table_name' => 'it',
        'dict_cc_code' => 'IT',
        'unicode_emoji' => '🇮🇹',
    ],
    'japanese' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => false,
        'deepl_code' => 'JA',
        'libre_translate_code' => 'ja',
        'my_memory_code' => 'ja',
        'website_import_support' => true,
        'jellyfin_code' => 'jpn',
        'database_dictionary_table_name' => 'jp',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇯🇵',
    ],
    'korean' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'KO',
        'libre_translate_code' => 'ko',
        'my_memory_code' => 'ko-KR',
        'website_import_support' => true,
        'jellyfin_code' => 'kor',
        'database_dictionary_table_name' => 'ko',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇰🇷',
    ],
    'latin' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'la',
        'website_import_support' => false,
        'jellyfin_code' => 'lat',
        'database_dictionary_table_name' => 'la',
        'dict_cc_code' => 'LA',
        'unicode_emoji' => '🇻🇦',
    ],
    'latvian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'LV',
        'libre_translate_code' => 'lv',
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => null,
        'dict_cc_code' => null,
        'unicode_emoji' => '🇱🇻',
    ],
    'lithuanian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'LT',
        'libre_translate_code' => 'lt',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => 'lit',
        'database_dictionary_table_name' => 'lt',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇱🇹',
    ],
    'macedonian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'mk',
        'website_import_support' => true,
        'jellyfin_code' => 'mac',
        'database_dictionary_table_name' => 'mk',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇲🇰',
    ],
    'norwegian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'NB',
        'libre_translate_code' => 'nb',
        'my_memory_code' => 'no',
        'website_import_support' => true,
        'jellyfin_code' => 'nor',
        'database_dictionary_table_name' => 'no',
        'dict_cc_code' => 'NO',
        'unicode_emoji' => '🇳🇴',
    ],
    // 'persian' => [
    //     'website_import_support' => true,
    // ],
    'polish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'PL',
        'libre_translate_code' => 'pl',
        'my_memory_code' => 'pl',
        'website_import_support' => true,
        'jellyfin_code' => 'pol',
        'database_dictionary_table_name' => 'pl',
        'dict_cc_code' => 'PL',
        'unicode_emoji' => '🇵🇱',
    ],
    'portuguese' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'PT-PT',
        'libre_translate_code' => 'pt',
        'my_memory_code' => 'pt-PT',
        'website_import_support' => true,
        'jellyfin_code' => 'por',
        'database_dictionary_table_name' => 'pt',
        'dict_cc_code' => 'PT',
        'unicode_emoji' => '🇵🇹',
    ],
    'romanian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'RO',
        'libre_translate_code' => 'ro',
        'my_memory_code' => 'ro',
        'website_import_support' => true,
        'jellyfin_code' => 'rum', // rum is not a misspell
        'database_dictionary_table_name' => 'ro',
        'dict_cc_code' => 'RO',
        'unicode_emoji' => '🇷🇴',
    ],
    'russian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'RU',
        'libre_translate_code' => 'ru',
        'my_memory_code' => 'ru-RU',
        'website_import_support' => true,
        'jellyfin_code' => 'rus',
        'database_dictionary_table_name' => 'ru',
        'dict_cc_code' => 'RU',
        'unicode_emoji' => '🇷🇺',
    ],
    'serbian' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => 'sr',
        'my_memory_code' => null,
        'website_import_support' => true,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'sr',
        'dict_cc_code' => 'SR',
        'unicode_emoji' => '🇷🇸',
    ],
    'slovak' => [
        'linguacafe_support' => false,
        'tokenizer' => null,
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'SK',
        'libre_translate_code' => 'sk',
        'my_memory_code' => null,
        'website_import_support' => false,
        'jellyfin_code' => null,
        'database_dictionary_table_name' => 'sk',
        'dict_cc_code' => 'SK',
        'unicode_emoji' => '🇸🇰',
    ],
    'slovenian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'SL',
        'libre_translate_code' => 'sl',
        'my_memory_code' => 'sl',
        'website_import_support' => true,
        'jellyfin_code' => 'slv',
        'database_dictionary_table_name' => 'sl',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇸🇮',
    ],
    'spanish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'ES',
        'libre_translate_code' => 'es',
        'my_memory_code' => 'es-ES',
        'website_import_support' => true,
        'jellyfin_code' => 'spa',
        'database_dictionary_table_name' => 'es',
        'dict_cc_code' => 'ES',
        'unicode_emoji' => '🇪🇸',
    ],
    // 'swahili' => [
    //     'website_import_support' => true,
    // ],
    'swedish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'SV',
        'libre_translate_code' => 'sv',
        'my_memory_code' => 'sv-SE',
        'website_import_support' => true,
        'jellyfin_code' => 'swe',
        'database_dictionary_table_name' => 'sv',
        'dict_cc_code' => 'SV',
        'unicode_emoji' => '🇸🇪',
    ],
    'thai' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => false,
        'deepl_code' => null,
        'libre_translate_code' => 'th',
        'my_memory_code' => 'th',
        'website_import_support' => false,
        'jellyfin_code' => 'tha',
        'database_dictionary_table_name' => 'th',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇹🇭',
    ],
    'turkish' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'TR',
        'libre_translate_code' => 'tr',
        'my_memory_code' => 'tr-TR',
        'website_import_support' => true,
        'jellyfin_code' => 'tur',
        'database_dictionary_table_name' => 'tr',
        'dict_cc_code' => 'TR',
        'unicode_emoji' => '🇹🇷',
    ],
    'ukrainian' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => true,
        'words_separated_by_spaces' => true,
        'deepl_code' => 'UK',
        'libre_translate_code' => 'uk',
        'my_memory_code' => 'uk',
        'website_import_support' => true,
        'jellyfin_code' => 'ukr',
        'database_dictionary_table_name' => 'ua',
        'dict_cc_code' => null,
        'unicode_emoji' => '🇺🇦',
    ],
    // 'vietnamese' => [
    //     'website_import_support' => true,
    // ],
    'welsh' => [
        'linguacafe_support' => true,
        'tokenizer' => 'spacy',
        'install_required' => false,
        'words_separated_by_spaces' => true,
        'deepl_code' => null,
        'libre_translate_code' => null,
        'my_memory_code' => 'cy-GB',
        'website_import_support' => false,
        'jellyfin_code' => 'wel',
        'database_dictionary_table_name' => 'cy',
        'dict_cc_code' => null,
        'unicode_emoji' => '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    ],
];