import type { UpdateNote } from '@lctypes/updates/UpdateNote'

const updateNotes: UpdateNote[] = [
    {
        title: 'v0.15-beta',
        date: '2025-04-13',
        summary:
            'This update adds support for attaching images to words and phrases, and fixes several UI issues.',
        description: '',
        newFeatures: [
            'Added attachable images for words and phrases.',
            'Added an option to apply changes to every word level at the same time in the text styling settings.',
        ],
        bugFixes: [
            'Fixed spaces around symbols(punctuation marks, quote marks, parentheses) in text.',
            "Fixed missing spaces while copy-pasting from the review page's example sentence.",
            'Fixed minor plain text mode issues.',
            'Admin API page was displaying an empty DeepL character usage section when the default API key was used.',
        ],
        otherChanges: [
            'Theme user settings now has one single theme selection dropdown instead of two for different sections. Its default value now will be the currently selected theme.',
            "Users won't be forced to log in again after 2 hours.",
            'The laravel and the python servers will now run automatically in dev or production environments based on the docker compose files.',
        ],
    },
    {
        title: 'v0.14.1',
        date: '2025-03-19',
        summary: 'Small hotfix for broken settings.',
        description: '',
        newFeatures: [],
        bugFixes: [
            'v0.14 broke the database, and users only seen a blank page after login. This update should fix the issue.',
        ],
        otherChanges: [],
    },
    {
        title: 'v0.14',
        date: '2025-03-18',
        summary:
            'This update implements queue based imports running in the background, dictionary import progress bar, support for multiple translation services, and several other features and bugfixes.',
        description: '',
        newFeatures: [
            "Added queue based chapter imports. From now on you won't have to wait for your chapters to be imported, it will happen in the background. If you open a book, the chapters will be updated in real time after the importing is finished.",
            'Dictionary import progress bar now shows real time progress.',
            'Added new online translation service: MyMemories.',
            'Added new offline, self hosted translation service: LibreTranslate.',
            'Added an API to connect custom scripts and translation services to LinguaCafe.',
            'Replaced cookies with local storage. This means that your local settings will reset to default settings.',
            'Added level to hover vocabulary box for highlighted words.',
            'Added .webp support for book cover images.',
            'Added auto theme switching based on system theme.',
            'Added an export database button to the admin page.',
            'Added automatic daily database backups.',
            'Added a change password button to the user settings.',
            'Added a button that lets users delete all their data related to their selected language.',
            'Added a statistic that shows the users known unique lemmas.',
            'Added fully customizable interactive text styling.',
        ],
        bugFixes: [
            'Book word counts did not update after deleting a chapter.',
            "Text reader's light theme glossary word colors were not displayed correctly.",
            'Text reader\'s glossary displayed "2" instead of "new" for new words.',
            'Development tools page had incorrect background for light theme',
            'Book word count percentages were displayed incorrectly in empty books and chapters.',
            'Fixed inconsistencies in custom themes when the user selected different foreground color.',
            "The selected font type was not applied to the hover vocabulary's reading section.",
            "The selected font type was not applied to the text reader's title.",
        ],
        otherChanges: [
            'Updated to Laravel 11.',
            'Replaced default book cover image.',
            'Replaced switches with checkboxes on the vocabulary export page.',
            'Removed simple text parsing method. It was something needed before v0.1, because import times were very slow.',
        ],
    },
    {
        title: 'v0.13.3',
        date: '2024-09-02',
        summary: '',
        description: '',
        newFeatures: [],
        bugFixes: [
            'Fixed a bug on the review page that prevented reviewing words and phrases that had no example sentences.',
        ],
        otherChanges: [],
    },
    {
        title: 'v0.13.2',
        date: '2024-08-30',
        summary: 'Small hotfix for website import.',
        description: '',
        newFeatures: [],
        bugFixes: ['Fixed website import.'],
        otherChanges: [],
    },
    {
        title: 'v0.13.1',
        date: '2024-08-29',
        summary: 'Small hotfix for turkish.',
        description: '',
        newFeatures: [],
        bugFixes: ['Turkish temporary fix.'],
        otherChanges: [],
    },
    {
        title: 'v0.13',
        date: '2024-06-24',
        summary:
            'This update added support for multiple users, ebook import improvement, auto level up words feature, and several other features and bug fixes.',
        description: '',
        newFeatures: [
            'Added support for using remote MySQL server.',
            'Added an icon.',
            'Added support for multiple users.',
            "Added an import option for e-books that lets users order the chapters based on the e-book's spine metadata. In some rare cases, this will fix incorrect chapter order for imported e-books.",
            'Added an option to set preferred hover vocabulary position. Now it can appear both above or below the hovered words based on the selected setting.',
            'Added filtering, sorting and pagination to the user settings, dictionary settings, font settings, library and chapters pages.',
            'Replaced the dictionary import process. Now users can import dictionaries by file upload, instead of having to copy files into the storage directory.',
            'Users now can delete and create DeepL dictionaries.',
            'Added support for DeepL translation into multiple languages.',
            'Added an option for % display of word counts on the chapters page.',
            "Added tabs to the text reader's settings dialog.",
            'Added an auto level words option, which automatically levels up words which the user did not click on while reading.',
            'Added a hotkey to the text reader to toggle plain text mode.',
            'Added settings to hide the subtitle timestamps and to change the space between subtitles.',
            'Added a setting to change the speed of the text to speech.',
        ],
        bugFixes: [
            'Login page sometimes showed an error despite a successful login, mostly after creating the first user.',
            'Review page displayed no text after the user finished reviewing if it only had one card in total.',
            'Fixed and enabled Thai import options.',
            'Added missing created_at and updated_at fields to imported words in the database.',
            'Fixed multi word touch selection with Apple pencils.',
            "Hover vocabulary now will move if there's not enough space for it to be displayed inside the reading area.",
            'Admin settings cannot be saved anymore if a field is left empty.',
            'Removed whitespace from the beginning of the tab selector UI element on mobile.',
            'Removed furigana from text on plain text mode.',
            'Fixed a problem when a user selected a long phrase, and the search result overflowed its box. I hid the whole search result if it was too long, and users now can see the whole search result by hovering over the shortened form.',
        ],
        otherChanges: [
            "Hover vocabulary's dictionary search results have been limited to 9 instead of 15. I'll add a setting for this in the future.",
            'JMDict dictionary files have been replaced with a single .zip file that contains them.',
        ],
    },
    {
        title: 'v0.12.6',
        date: '2024-06-05',
        summary: 'Small hotfix for multi device use.',
        description: '',
        newFeatures: [],
        bugFixes: [
            'Using the same LinguaCafe user on multiple devices with multiple languages caused database corruption in some very rare edge cases. Now whenever a user logs in on a device, other devices will be logged out to avoid this issue. This is a temporary solution.',
        ],
        otherChanges: [],
    },
    {
        title: 'v0.12.5',
        date: '2024-06-01',
        summary: 'Security issue hotfix.',
        description: '',
        newFeatures: [],
        bugFixes: ['Fixed a serious security issue.'],
        otherChanges: [],
    },
    {
        title: 'v0.12.4',
        date: '2024-05-29',
        summary: 'Small hotfix for broken goal tracking.',
        description: '',
        newFeatures: [],
        bugFixes: ['Fixed unusable Spanish goals after creating the first user.'],
        otherChanges: [],
    },
    {
        title: 'v0.12.3',
        date: '2024-05-22',
        summary: 'Small hotfix for fonts.',
        description: '',
        newFeatures: [],
        bugFixes: ['Fixed Polish font file name, which did not load previously.'],
        otherChanges: [],
    },
    {
        title: 'v0.12.2',
        date: '2024-05-19',
        summary: 'Small hotfix for UI problems.',
        description: '',
        newFeatures: [],
        bugFixes: [
            'Disabled touch scrolling while selecting text.',
            'Fixed a bug that prevented reading and reviewing in browsers that do not support TTS, like Opera.',
        ],
        otherChanges: [],
    },
    {
        title: 'v0.12.1',
        date: '2024-05-17',
        summary: 'Small hotfix for missing folder creation and UI.',
        description: '',
        newFeatures: [],
        bugFixes: [
            'Example sentence text overflowed the review card.',
            'Added missing folder creation for linguacafe/storage/app/temp. Not having it caused ebook file imports, and Japanese language install to fail.',
        ],
        otherChanges: [],
    },
    {
        title: 'v0.12',
        date: '2024-05-17',
        summary:
            'This update introduced better installation process, browser tts support, progressive web app support, fonts, and several bug fixes.',
        description: '',
        newFeatures: [
            'Docker installation and update process has been improved. It does not require git and chmod commands anymore (except once for already existing users).',
            'Added book length to the library list view.',
            'Added word inflections table for Japanese.',
            'Added text to speech option for the text reader.',
            'Added bottom sheet vocabulary for mobile view.',
            'Added progressive web app support. Now users can use LinguaCafe as a full screen mobile app.',
            'Added font type management system.',
        ],
        bugFixes: [
            'Added missing kanji images. Now users can see the kanji stroke order and writing animation on the kanji info pages.',
            'Book word counts now update after importing something.',
            'Hover vocabulary now disappears when the user moves their mouse pointer to empty space.',
            'Importing texts now skips too long words instead of throwing an error.',
            'Importing dictionaries now skips records that contain a word or a definition that is too long instead of throwing an error.',
            'Fixed highlighted word colors that were displayed incorrectly at several places.',
            'Interactive text is not selectable anymore on the review page natively like other texts in the browser.',
            'Previous example sentences are not visible anymore on the review page while the new one is loading.',
            'Users cannot open a chapter in the text reader anymore that does not belong to their selected language.',
            "JMDict's source language is not editable anymore.",
            "Copying a selected word with ctrl+c won't set the word's level to new anymore.",
            'It is now impossible to create a phrase without any words, which would corrupt the database.',
            "Fixed light theme's warning color, because it was too yellow and lacking in contrast. For devices that already opened LinguaCafe, users must click on the reset color button to update it.",
            'Fixed plain text mode copy-paste in Firefox.',
            "Symbols won't be combined anymore with words in Japanese. This only applies to texts that are imported after this update.",
            'Fixed a bug that caused text importing to fail in Japanese, if the last word was combined with the previous word during post processing.',
            'Polish language had a font type that displayed incorrect letters.',
        ],
        otherChanges: [
            "The import dialog won't close by itself anymore after importing has finished.",
            'Laravel now produces more detailed logs, and logs both to the log file and the docker terminal.',
        ],
    },
    {
        title: 'v0.11.3',
        date: '2024-05-08',
        summary: 'Small review hotfix.',
        description: '',
        newFeatures: [],
        bugFixes: ['Fixed a bug that caused practice review mode to be always turned off.'],
        otherChanges: [],
    },
    {
        title: 'v0.11.2',
        date: '2024-04-27',
        summary: 'Small hotfix for text reader bugs.',
        description: '',
        newFeatures: [],
        bugFixes: [
            'Fixed annoying multi word text selection bug.',
            'Fixed furigana.',
            'Fixed plain text mode.',
        ],
        otherChanges: [],
    },
    {
        title: 'v0.11.1',
        date: '2024-04-27',
        summary: 'Small hotfix for word highlighting settings.',
        description: '',
        newFeatures: [],
        bugFixes: [
            'Fixed broken "Hide all highlighting" and "Hide new word highlighting" settings.',
        ],
        otherChanges: [],
    },
    {
        title: 'v0.11',
        date: '2024-04-25',
        summary:
            'This update added several new languages, and introduced a language install feature to reduce docker image size.',
        description: '',
        newFeatures: [
            'Language installation. Some languages have been removed from the docker image to reduce its size, and became installable on the admin page.',
            'Added new languages: Croatian, Danish, Macedonian, Polish, Portuguese, Romanian, Slovenian, Thai and Turkish.',
        ],
        bugFixes: [],
        otherChanges: ['The default language has been changed to Spanish.'],
    },
    {
        title: 'v0.10.1',
        date: '2024-04-21',
        summary: 'Small hotfix for hotkeys.',
        description: '',
        newFeatures: [],
        bugFixes: ['Fixed a bug that disabled some hotkeys.'],
        otherChanges: [],
    },
    {
        title: 'v0.10',
        date: '2024-04-19',
        summary: 'This update added theme customization, ui improvements and several bug fixes.',
        description: '',
        newFeatures: [
            'Added a new default list layout for the library page.',
            'Added a logout confirmation dialog.',
            'Added theme customization.',
            'Added different background colors for different word levels.',
            "Added a separate color for ignored words' text color.",
            "Added a hotkey to set words' level back to new.",
        ],
        bugFixes: [
            'There will be no error message anymore due to empty book name when you click on "Create book" button.',
            "While creating a book, the save button won't be grayed out anymore if you type in a name. Previously it only turned active after you removed the focus from the name input field.",
            'While creating or editing a book and uploading an image, clicking on the cancel button will now revert the image to the default or previous image, instead of showing an error message.',
            'Fixed a bug that caused words imported on the vocabulary page to not be added to the review system.',
            'Pressing the enter key when creating or editing a book or a chapter now will act the same as clicking on the Save button. Pressing the enter key when importing something now will act as the Continue or Import button.',
            'Fixed a bug that caused hover vocabulary box to appear even when plain text mode was active',
        ],
        otherChanges: [
            'Improved dictionary search UI: made dictionary colors less distracting and vocabulary sidebar more compact and uniform.',
            'The online user manual has been moved from the GitHub Page to the GitHub Wiki. It also moved from a Vuetify format to Markdown.',
            'DeepL API key error will not appear on the admin page anymore if it set to the default value.',
            'Added a warning on how hover vocabulary box works in review settings.',
            'Lightened default dark mode text color to make it more readable.',
            'Made navigation sidebar more compact.',
        ],
    },
    {
        title: 'v0.9',
        date: '2024-03-28',
        summary: 'This update added new languages, new dictionaries and improved review options.',
        description: '',
        newFeatures: [
            'Added new supported languages: English, Greek and Latin.',
            'Made text editable when importing a website.',
            'Added settings dialog for the review page.',
            'Expanded example sentence mode on the review page. Now it has 3 options: disabled, plain text and interactive text.',
            'Added hover vocabulary on the review page.',
            'Added dictionary edit dialog for the admin page.',
            "DeepL translator's target language now can be changed.",
            'Added support for HanDeDict dictionary.',
            'Added support for every dict cc dictionary. Now you can import multiple of them for the same language.',
        ],
        bugFixes: [],
        otherChanges: ['MacOS users have a new, simpler install and update process.'],
    },
    {
        title: 'v0.8',
        date: '2024-03-21',
        summary:
            'This update added website import, review improvements and a user manual along with a lot of bug fixes.',
        description: '',
        newFeatures: [
            'Added "website" import option.',
            'Added vocabulary word import from .csv.',
            'Added start review dialog for the review button in the navigation sidebar.',
            'Added review finished information cards, instead of redirecting the user to the homepage.',
            'Word counts now load automatically when you open a book.',
            "Added a setting for hover vocabulary's delay.",
            'Added user manual. Will be extended and updated regularly.',
        ],
        bugFixes: [
            "Review cards' content overflowed the buttons.",
            'Books with long titles hid their open button.',
            'Daily read words goal was not updating while reviewing phrases if the sentence mode was not selected.',
            'Vocabulary sidebar had a minor visual problem with its edges.',
            'Text reader had an error if the opened chapter had no text.',
            'Renamed label "stage" to "level" on vocabulary page to make it consistent.',
            'Non Chinese and Japanese phrases were only searchable on the vocabulary page without spaces. This fix only applies to phrases created after this update.',
            'Non Chinese and Japanese phrases were displayed incorrectly on the vocabulary sidebar.',
            'Phrases were displayed incorrectly on the vocabulary export dialog.',
            "Reading fields were visible on vocabulary search page's edit dialog for languages that had no readings.",
            'Numpad hotkeys were not working.',
            "Hover vocabulary's search dictionary setting was not working when it was turned off.",
            'Hover vocabulary sent a request to the server even if you took the mouse off from the hovered word before the delay ended.',
        ],
        otherChanges: [
            "If DeepL is disabled for a language, the dictionaries will not show a DeepL error message anymore, and they also won't make a request to retrieve the DeepL translations.",
            'For better performance and to avoid accidentaly opening hover vocabulary on words, a slight delay was added before the hover vocabulary box becomes visible. The dictionary and DeepL searches already had this delay, it just has been applied to the visibility of the hover vocabulary box as well.',
        ],
    },
    {
        title: 'v0.7',
        date: '2024-02-14',
        summary:
            'This update replaced the Python Django server with Bottle for better performance and introduced dynamic language model loading to decrease memory usage. It also added several new import options and enhancements to the hover vocabulary box.',
        description: '',
        newFeatures: [
            'Replaced the python Django server with Bottle for better performance.',
            'Added dynamic language model loading. Models are only going to be loaded at the first import for each language. This will significantly decrease memory use based on which and how many langauges are used on a server after its startup.',
            "Added new 'Plain text' import option.",
            "Added new 'Text file' import option.",
            "Added new 'Jellyfin subtitle' import option.",
            "Added new 'Subtitle file' import option.",
            "Setting words' and phrases' level is now possible while hovering over them.",
            'Added dictionary search for hover vocabulary box.',
            'Added DeepL search for hover vocabulary box.',
            "Separated DeepL search from regular dictionary search in the vocabulary box. Users won't have to wait for DeepL server's response to see the dictionary search results which load much faster.",
            'Added loading indicator for vocabulary box dictionary search.',
            'Added an option to automatically highlight a word when it gets a translation added to it.',
            'A list of words which were not counted in the statistics now will be automatically set to ignored when imported. Also added all numbers and more symbols to the list.',
            "Vocabulary search page's edit dialog now will close on its own after saving it, and the search results will be updated automatically.",
            'Added chapter length option to import dialog.',
            'Added hotkeys for text scrolling.',
            'The selected library layout will now be remembered.',
            'Added option to change the default MySQL database and user.',
            'Added windows installation guide and installation file.',
        ],
        bugFixes: [
            'Fixed a bug that caused the records on the vocabulary search page to appear in random order inside the specified order by parameter.',
            'Fixed an issue in the text reader glossary, where empty parentheses were visible in languages that have no readings.',
            "Fixed a visual issue where the scrollbars' background were a different color than the area they were placed on.",
            'Fixed an issue that caused long chapter titles to hide the text.',
            'Furigana now displays the editable reading field. Previously it displayed the reading that was assigned to the exact word in text while importing it.',
            'Fixed a visual issue where the day text was not visible in the calendar while using dark theme.',
            'Added missing lemma to review card when using example sentence mode.',
            'Removed furigana from e-book imports.',
        ],
        otherChanges: [
            'Removed media player page, as it has been replaced with Jellyfin subtitle import option.',
            'Improved text selecting design.',
            'Removed unnecessary files from the webserver image and decreased its size.',
        ],
    },
    {
        title: 'v0.6',
        date: '2024-01-29',
        summary:
            'This version introduced a fixed sidebar vocabulary for wider screens and a minimalistic hover vocabulary box. It also added YouTube subtitle import and hotkeys for the text reader and review pages.',
        description: '',
        newFeatures: [
            'Added an always open and fixed sidebar vocabulary as a default option for screens wider than 960px. It can be turned off in the text reader settings.',
            'Added a minimalistic vocabulary box, that appears when the user moves the mouse over a word. It can be turned off in the text reader settings.',
            'Added youtube subtitle import option.',
            'Added hotkeys for the text reader and review pages.',
            'Added proper finish reading screen.',
        ],
        bugFixes: [
            'Users clicking anywhere outside of the vocabulary box will close the vocabulary box. Previously it only worked if the user clicked on an empty space inside the text box.',
            'Increased maximum execution time for importing dictionaries. If your dictionary import did not end with a success message but still functional, I recommend importing it again, because it probably did not import all the records from the dictionary file.',
        ],
        otherChanges: ['Updated node.js to v20.11.0.'],
    },
    {
        title: 'v0.5.2',
        date: '2024-01-23',
        summary:
            'This was a bug fix release that addressed a problem with deployment and included a simple migration guide.',
        description: '',
        newFeatures: [],
        bugFixes: ['Fixed a problem with deployment, and added a simple migration guide.'],
        otherChanges: [],
    },
    {
        title: 'v0.5.1',
        date: '2024-01-22',
        summary:
            'This was a bug fix release that solved a problem which prevented lemmas and lemma readings from being saved.',
        description: '',
        newFeatures: [],
        bugFixes: ['Fixed a bug that prevented lemmas end lemma readings to be saved.'],
        otherChanges: [],
    },
    {
        title: 'v0.5',
        date: '2024-01-21',
        summary:
            "Lemma modifications only apply to new words that haven't been imported yet. There will be an option in the future, to overwrite already existing lemmas.",
        description: `The docker installation process has been improved since the last version. Fixed all the known issues with it, and removed the requirement for users to create their folders manually and to modify the docker-compose.yml file.<br /><br /> There were several issues with Jellyfin integration. Now it should work properly with every language and video type. Also added information about subtitle file naming to the readme file.<br /><br /> Lemma modifications only apply to new words that haven't been imported yet. There will be an option in the future, to overwrite already existing lemmas.`,
        newFeatures: [
            'Added support for new languages: Czech and Welsh.',
            'Added Kengdic dictionary support for Korean.',
            'Added CC-CEDICT dictionary support for Chinese.',
            'Added Eurfa dictionary support for Welsh.',
            'Added pinyin support for Chinese.',
            'Added furigana support for Japanese.',
        ],
        bugFixes: [
            'Removed empty and duplicated records from dictionary search results.',
            'Added Chinese font type so every Chinese and Japanese text should be displayed with NotoSansSC and NotoSansJP font types.',
            'Removed word spacing from Chinese texts.',
            "Removed '+' symbol from Korean lemmas.",
            "Removed 'die/der/das' from the beginning of German search terms for better results.",
            'Fixed an issue with the Media player that only allowed TV Show subtitles to be displayed from Jellyfin; now every video type is playable.',
            'Fixed an issue with the Media player that caused every language to be handled as Japanese.',
            'Fixed an issue related to Media player missing language support; now all languages work with it.',
            'Fixed an issue on the vocabulary search page that caused phrases to be displayed with commas between the words, or with no spaces between them (further improvement is needed for non-Japanese and Chinese languages).',
            'Fixed an error that broke the Kanji page if you had no known Kanji yet from every category.',
            'Fixed dark theme style on color picker.',
            "Added a missing label to text reader's settings dialog.",
        ],
        otherChanges: [
            'Moved the dictionary search to the main section of the popup vocabulary.',
            'Removed all online dependencies.',
            'Updated language selection dialog design, and the supported languages information in the readme.',
            'Changed chapter size from 9000 to 4000 characters for importing e-books due to performance issues. There will be an option to edit this limit soon.',
            'Unified text reader and subtitle reader settings.',
            'Added dynamic subtitle rendering for Media player, which increased performance significantly. For this I had to remove customizable spacing between subtitles, due to a bug that moved the vocabulary box around. This will be fixed in the future.',
        ],
    },
    {
        title: 'v0.4',
        date: '2024-01-15',
        summary:
            'German lemmatization was improved, and a new UI page was added to simplify and manage dictionary imports. The Docker installation and update process was also simplified significantly.',
        description: '',
        newFeatures: [
            'German lemmatization for nouns and separable verbs have been improved.',
            'Importing dictionaries have been simplified, and has a new UI page to manage them.',
            'Information popups for different features have been added.',
        ],
        bugFixes: [
            'Added missing toolbar titles on the review page.',
            'Added missing dialog close buttons.',
            'Auto generated lemmas were changed to only contain lowercase letters, instead of sometimes having uppercase letters.',
        ],
        otherChanges: [
            'Docker images are now published on the GitHub Container Registry, and there is a much simpler installation and update process.',
            'Changed version number format.',
            'Updated MySQL image to 8.0.',
        ],
    },
    {
        title: 'v0.3',
        date: '2024-01-12',
        summary:
            'This update added partial support for Russian, Swedish, and Ukrainian. It also reworked the Docker installation process and split the "Highlight words" setting into two separate options for more control over highlighting.',
        description: '',
        newFeatures: [
            'Added partial support for new languages: Russian, Swedish and Ukrainian.',
            'Docker installation and update process has been reworked and made simpler.',
            'The "Highlight words" option in the text and subtitle reader settings dialog has been split into "Hide all highlighting" and "Hide new word highlighting" to make it possible to hide only the yellow new word highlighting.',
        ],
        bugFixes: [
            'Fixed all issues with "Plain text mode".',
            'Fixed a bug that caused words to only have top and bottom border without background when "Highlight words" option was turned off, and the user hovered over them.',
            'Missing toolbar titles have been added to text reader.',
            'A non-standard scroll function that caused issues in some browsers has been fixed and added as an option for text and subtitle reader.',
            'An issue has been fixed that caused white space characters being displayed as clickable words on the text reader page, and it broke the software if the user clicked on them.',
        ],
        otherChanges: [
            'The "/storage/app/dictionaries" folder has been created in the repository, and won\'t have to be created manually.',
            'All tokenizer models have been replaced with smaller sized ones due to possible performance issues. They will be replaced with larger models for specific languages if it causes word tagging accuracy issues.',
        ],
    },
    {
        title: 'v0.2',
        date: '2024-01-09',
        summary:
            'This update added partial support for Chinese, Dutch, Finnish, French, Italian, and Korean. It also fixed a bug with the DeepL translator.',
        description: '',
        newFeatures: [
            'Added partial support for new languages: Chinese, Dutch, Finnish, French, Italian and Korean.',
        ],
        bugFixes: [
            'Fixed a bug that caused DeepL translator to handle all languages as Norwegian.',
        ],
        otherChanges: ['The selected language is displayed as capitalized text.'],
    },
    {
        title: 'v0.1',
        date: '2024-01-07',
        summary: 'Initial release of the application.',
        description: 'Release.',
        newFeatures: [],
        bugFixes: [],
        otherChanges: [],
    },
]

export default updateNotes
